server:
  port: 8081
  servlet:
    context-path: /v1
    encoding:
      charset: UTF-8
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toyproject_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update

logging:
  pattern:
    console: "[ %d{ HH:mm:ss.SSS } ][ %-5level ][ %logger.%method:line%line ] - %msg%n"