CREATE SCHEMA `MBTI_CHAT` ;
DROP TABLE IF EXISTS `MBTI_CHAT`.`CHAT_MESSAGE`;
CREATE TABLE `MBTI_CHAT`.`CHAT_MESSAGE` (
	`MESSAGE_ID`	BIGINT	NOT NULL AUTO_INCREMENT,
	`CHAT_ROOM_ID`	BIGINT	NOT NULL,
	`MESSAGE`	TEXT	NULL,
	`MESSAGE_TIME`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`USER_ID`	BIGINT	NULL,
	PRIMARY KEY (`MESSAGE_ID`)
);
DROP TABLE IF EXISTS `MBTI_CHAT`.`CHAT_ROOM`;
CREATE TABLE `MBTI_CHAT`.`CHAT_ROOM` (
	`CHAT_ROOM_ID`	BIGINT	NOT NULL AUTO_INCREMENT,
	`HOST_ID`	BIGINT	NULL,
	`MBTI`	VARCHAR(10)	NULL,
	`MBTI_CHECK`	BOOLEAN	NULL,
	`MAX_NUM`	INTEGER	NULL,
	`CREATION_TIME`	DATETIME	DEFAULT CURRENT_TIMESTAMP,
	`NUM`	INTEGER	NULL,
	`CHAT_SUBJECT`	VARCHAR(255)	NULL,
	PRIMARY KEY (`CHAT_ROOM_ID`)
);