server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
   # driver-class-name: com.mysql.cj.jadbc.Driver
    url: jdbc:mysql://localhost:3306/mbur?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111


