server:
  port: 8082
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
   # driver 이름을 자동으로 찾아주기 때문에 이름 설정을 할 필요가 없다.
   # driver-class-name: com.mysql.cj.jadbc.Driver
    url: jdbc:mysql://localhost:3306/mbur?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111

